on: [push, pull_request]

name: CMake

jobs:
  cmake-build:
    name: CMake ${{ matrix.os }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        build_type: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v4

    - name: "[Shared] Configure CMake"
      run: cmake --preset=${{ matrix.build_type }}-Shared -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/${{ matrix.build_type }}-Shared/install/

    - name: "[Shared] Build"
      run: cmake --build ${{github.workspace}}/build/${{ matrix.build_type }}-Shared

    - name: "[Shared] Install"
      run: cmake --install ${{github.workspace}}/build/${{ matrix.build_type }}-Shared

    - name: "[Static] Configure CMake"
      run: cmake --preset=${{ matrix.build_type }}-Static -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/${{ matrix.build_type }}-Static/install/

    - name: "[Static] Build"
      run: cmake --build ${{github.workspace}}/build/${{ matrix.build_type }}-Static

    - name: "[Static] Install"
      run: cmake --install ${{github.workspace}}/build/${{ matrix.build_type }}-Static
