on: [push, pull_request]

name: CMake

jobs:
  cmake-build:
    name: CMake ${{ matrix.os }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        build_type: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v4

    - name: "[Shared] Configure CMake"
      if: matrix.os != 'windows-latest'
      run: cmake -B build/shared -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=build/shared/install/ ${{ matrix.os_configure_flags }} -DBUILD_SHARED_LIBS=ON

    - name: "[Shared] Build"
      if: matrix.os != 'windows-latest'
      run: cmake --build build/shared --config ${{ matrix.build_type }}      

    - name: "[Shared] Install"
      if: matrix.os != 'windows-latest'
      run: cmake --install build/shared --config ${{ matrix.build_type }}

    - name: "[Static] Configure CMake"
      if: matrix.os != 'windows-latest'
      run: cmake -B build/static -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=build/static/install/ ${{ matrix.os_configure_flags }} -DBUILD_SHARED_LIBS=OFF

    - name: "[Static] Build"
      if: matrix.os != 'windows-latest'
      run: cmake --build build/static --config ${{ matrix.build_type }}      

    - name: "[Static] Install"
      if: matrix.os != 'windows-latest'
      run: cmake --install build/static --config ${{ matrix.build_type }}


    - name: "[Static+Shared] Configure CMake"
      if: matrix.os == 'windows-latest'
      run: cmake -B build/multi -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=build/static/install/ ${{ matrix.os_configure_flags }} -DBUILD_SHARED_LIBS=ON

    - name: "[Static+Shared] Build"
      if: matrix.os == 'windows-latest'
      run: cmake --build build/multi --config ${{ matrix.build_type }}      

    - name: "[Static+Shared] Install"
      if: matrix.os == 'windows-latest'
      run: cmake --install build/multi --config ${{ matrix.build_type }}
